
export const metadata = {
  title: "Home page test app",
  description: "Generated by Karfa",
};

const Home = () => {
  return (
    <div className="  p-2 text-cyan-50" >Home
    
    <div class="btn-group-vertical" role="group" aria-label="">
      <button type="button" class="btn btn-secondary">First One</button>
      <button type="button" class="btn btn-secondary">Second One</button>
      <div class="btn-group" role="group">
        <button
          id="dropdownId"
          type="button"
          class="btn btn-secondary dropdown-toggle"
          data-bs-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          More
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownId">
          <a class="dropdown-item" href="#">First Dropdown</a>
          <a class="dropdown-item" href="#">Second Dropdown</a>
        </div>
        
<div className="grid grid-cols-5 grid-rows-5 gap-4">
    <div className="row-span-2 bg-amber-50">1</div>
    <div className="col-span-2 bg-amber-100 ">2</div>
    <div className="row-span-3 col-start-2 row-start-2 bg-amber-200">3</div>
    <div className="col-span-2 row-span-2 col-start-3 row-start-2 bg-amber-300">4</div>
    <div className="col-start-3 row-start-4 bg-amber-400">5</div>
    <div className="row-span-3 col-start-1 row-start-3 bg-amber-600">6</div>
    <div className="col-span-2 col-start-2 row-start-5 bg-amber-700">7</div>
    <div className="col-span-2 row-span-2 col-start-4 row-start-4 bg-amber-800">8</div>
    <div className="row-span-2 col-start-5 row-start-1 bg-amber-900">10</div>
    <div className="col-start-5 row-start-3 bg-amber-900">11</div>
    <div className="col-start-4 row-start-1 bg-red-900">12</div>
</div>



<div className="grid grid-cols-5 grid-rows-5 gap-4">
    <div className="row-span-2 bg-amber-500">1</div>
    <div className="row-span-4 col-start-2 row-start-8 bg-amber-500">2</div>
    <div className="col-span-2 row-span-3 col-start-4 row-start-10 bg-amber-500">3</div>
</div>
    
      </div>
    </div>
    
    
    </div>
  )
}

export default Home