spring.application.name=Drasta

spring.data.mongodb.uri=mongodb://localhost:27017/drasta
#spring.data.mongodb.uri=mongodb://192.168.0.185:27017/drasta?directConnection=true&appName=mongosh+2.4.0

cloudinary.cloud.name = dfs8jfgui
cloudinary.api.key = 347717419372822
cloudinary.secret.key = YLgiS4xOAplH79GEl8D7Q3d2eXQ

#server.port = 7072

#for disabled the inbuilt size
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

JWT_SECRET_KEY=6HAg85U8YIzB0Cl1wPmJ61+21EfExzcRt1MYVktpLilWNvjWfttvjAFdLVaefwApGJBviaYf4hwsyoHL+MC7pQ==

spring.mail.host=smtp.gmail.com
#spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=vaisdt14.webbixel@gmail.com
spring.mail.password=baxf cvil ktrr awup
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#for localhost
#app.frontend.reset-url = http://localhost:5173/reset-password/

#//for production
app.frontend.reset-url = https://drasta.pages.dev/reset-password/

# PhonePe Configuration
phonepe.merchant.id=PGTESTPAYUAT86
phonepe.merchant.key=96434309-7796-489d-8924-ab56988a6076

#for production
#phonepe.api.url=https://api.phonepe.com/apis/hermes

#for testing
phonepe.api.url=https://api-preprod.phonepe.com/apis/pg-sandbox

# Application Configuration
app.callback.url=http://localhost:8080

#logging.level.org.springframework.web=DEBUG
#logging.level.org.apache.catalina=DEBUG



#for GraphQL
# Enable GraphiQL UI
graphiql.enabled=true
graphiql.endpoint=/graphql
graphiql.mapping=/graphiql
