import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { api } from "@/db/api";
import { ArrowLeft, Printer, Download, Phone, Mail, MapPin } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";
import { formatCurrency } from "@/lib/utils";
import * as XLSX from 'xlsx';

import { getBusinessSettings } from "@/db/settingsApi";
import type { BusinessSettings } from "@/types/types";

export default function CustomerLedger() {
  const { customerId } = useParams<{ customerId: string }>();
  const navigate = useNavigate();
  const [ledgerData, setLedgerData] = useState<any>(null);
  const [settings, setSettings] = useState<BusinessSettings | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (customerId) {
      loadData();
    }
  }, [customerId]);

  const loadData = async () => {
    try {
      setLoading(true);
      const [ledger, settingsData] = await Promise.all([
        api.customers.getLedger(customerId!),
        getBusinessSettings()
      ]);
      setLedgerData(ledger);
      setSettings(settingsData);
    } catch (error) {
      console.error("Error loading data:", error);
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadExcel = () => {
    if (!ledgerData) return;

    const workbook = XLSX.utils.book_new();

    // Customer Summary Sheet
    const summaryData = [
      ['Customer Ledger Report'],
      ['Generated by ' + (settings?.company_name || 'Mit Electro World')],
      [''],
      ['Customer Code', ledgerData.customer.customer_code],
      ['Customer Name', ledgerData.customer.full_name],
      ['Mobile', ledgerData.customer.mobile_primary],
      ['Email', ledgerData.customer.email || '-'],
      [''],
      ['Financial Summary'],
      ['Total Disbursed', ledgerData.totalDisbursed],
      ['Total Paid', ledgerData.totalPaid],
      ['Total Outstanding', ledgerData.totalOutstanding],
      [''],
    ];

    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

    // Loans Sheet
    const loansData: any[] = [
      ['Loan ID', 'Product', 'Principal', 'Interest', 'Total Amount', 'Paid', 'Outstanding', 'Status'],
    ];

    ledgerData.loans.forEach((loanDetail: any) => {
      loansData.push([
        loanDetail.loan.loan_id,
        loanDetail.product?.model || '-',
        loanDetail.loan.principal_amount,
        loanDetail.loan.total_interest,
        loanDetail.loan.total_payable_amount,
        loanDetail.summary.totalPaid,
        loanDetail.summary.totalOutstanding,
        loanDetail.loan.status,
      ]);
    });

    const loansSheet = XLSX.utils.aoa_to_sheet(loansData);
    XLSX.utils.book_append_sheet(workbook, loansSheet, 'Loans');

    // Payments Sheet
    const paymentsData: any[] = [
      ['Date', 'Loan ID', 'Amount', 'Mode', 'Reference'],
    ];

    ledgerData.loans.forEach((loanDetail: any) => {
      loanDetail.payments.forEach((payment: any) => {
        paymentsData.push([
          payment.payment_date,
          loanDetail.loan.loan_id,
          payment.amount_paid,
          payment.payment_mode,
          payment.transaction_reference || '-',
        ]);
      });
    });

    const paymentsSheet = XLSX.utils.aoa_to_sheet(paymentsData);
    XLSX.utils.book_append_sheet(workbook, paymentsSheet, 'Payments');

    // Download
    XLSX.writeFile(workbook, `Customer_Ledger_${ledgerData.customer.customer_code}_${new Date().toISOString().split('T')[0]}.xlsx`);
  };

  const getStatusBadge = (status: string) => {
    const variants: Record<string, "default" | "secondary" | "destructive"> = {
      active: "default",
      completed: "secondary",
      defaulted: "destructive",
    };
    return (
      <Badge variant={variants[status] || "secondary"}>
        {status.toUpperCase()}
      </Badge>
    );
  };

  if (loading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-12 w-full bg-muted" />
        <Skeleton className="h-64 w-full bg-muted" />
        <Skeleton className="h-96 w-full bg-muted" />
      </div>
    );
  }

  if (!ledgerData) {
    return (
      <div className="text-center py-12">
        <p className="text-muted-foreground">Customer not found</p>
        <Button onClick={() => navigate('/customers')} className="mt-4">
          Back to Customers
        </Button>
      </div>
    );
  }

  const { customer, loans, totalDisbursed, totalPaid, totalOutstanding } = ledgerData;

  return (
    <div className="space-y-6">
      {/* Header - Hide on print */}
      <div className="flex items-center justify-between print:hidden">
        <div className="flex items-center gap-4">
          <Button variant="outline" size="icon" onClick={() => navigate('/customers')}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div>
            <h1 className="text-3xl font-bold">Customer Ledger</h1>
            <p className="text-muted-foreground">Complete financial statement</p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleDownloadExcel}>
            <Download className="mr-2 h-4 w-4" />
            Download Excel
          </Button>
          <Button onClick={handlePrint}>
            <Printer className="mr-2 h-4 w-4" />
            Print
          </Button>
        </div>
      </div>

      {/* Print Header - Show only on print */}
      <div className="hidden print:block text-center mb-6">
        <h1 className="text-2xl font-bold">{settings?.company_name || 'Mit Electro World'}</h1>
        <p className="text-sm text-muted-foreground">Customer Ledger Report</p>
        <p className="text-xs text-muted-foreground">
          {settings?.tagline}
        </p>
        <p className="text-xs text-muted-foreground mt-1">
          {settings?.address_line1}, {settings?.city}
        </p>
        <p className="text-xs text-muted-foreground">
          Generated on: {new Date().toLocaleString()}
        </p>
      </div>

      {/* Customer Information */}
      <Card>
        <CardHeader>
          <CardTitle>Customer Information</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <div>
              <p className="text-sm text-muted-foreground">Customer Code</p>
              <p className="font-semibold text-lg">{customer.customer_code}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Full Name</p>
              <p className="font-semibold text-lg">{customer.full_name}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Father's Name</p>
              <p className="font-medium">{customer.father_name || '-'}</p>
            </div>
            <div className="flex items-center gap-2">
              <Phone className="h-4 w-4 text-muted-foreground" />
              <div>
                <p className="text-sm text-muted-foreground">Mobile</p>
                <p className="font-medium">{customer.mobile_primary}</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Mail className="h-4 w-4 text-muted-foreground" />
              <div>
                <p className="text-sm text-muted-foreground">Email</p>
                <p className="font-medium">{customer.email || '-'}</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <MapPin className="h-4 w-4 text-muted-foreground" />
              <div>
                <p className="text-sm text-muted-foreground">City</p>
                <p className="font-medium">{customer.city || '-'}</p>
              </div>
            </div>
          </div>

          {customer.current_address && (
            <div className="mt-4 pt-4 border-t">
              <p className="text-sm text-muted-foreground">Current Address</p>
              <p className="font-medium">{customer.current_address}</p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Financial Summary */}
      <Card>
        <CardHeader>
          <CardTitle>Financial Summary</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="p-4 bg-blue-50 dark:bg-blue-950 rounded-lg">
              <p className="text-sm text-muted-foreground mb-1">Total Disbursed</p>
              <p className="text-2xl font-bold text-blue-600 dark:text-blue-400">
                {formatCurrency(totalDisbursed)}
              </p>
            </div>
            <div className="p-4 bg-green-50 dark:bg-green-950 rounded-lg">
              <p className="text-sm text-muted-foreground mb-1">Total Paid</p>
              <p className="text-2xl font-bold text-green-600 dark:text-green-400">
                {formatCurrency(totalPaid)}
              </p>
            </div>
            <div className="p-4 bg-orange-50 dark:bg-orange-950 rounded-lg">
              <p className="text-sm text-muted-foreground mb-1">Total Outstanding</p>
              <p className="text-2xl font-bold text-orange-600 dark:text-orange-400">
                {formatCurrency(totalOutstanding)}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Loans Details */}
      {loans.map((loanDetail: any, index: number) => (
        <Card key={loanDetail.loan.id || index} className="break-inside-avoid">
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle className="text-lg">
                Loan #{index + 1} - {loanDetail.loan.loan_id}
              </CardTitle>
              {getStatusBadge(loanDetail.loan.status)}
            </div>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Loan Basic Info */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div>
                <p className="text-sm text-muted-foreground">Product</p>
                <p className="font-medium">
                  {loanDetail.product?.model || (loanDetail.product?.brand ? `${loanDetail.product.brand}` : '-')}
                </p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Loan Type</p>
                <p className="font-medium">{loanDetail.loan.loan_type?.toUpperCase()}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Start Date</p>
                <p className="font-medium">
                  {new Date(loanDetail.loan.start_date).toLocaleDateString()}
                </p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Tenure</p>
                <p className="font-medium">{loanDetail.loan.tenure_months} months</p>
              </div>
            </div>

            {/* Loan Financial Breakdown */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-4 bg-muted rounded-lg">
              <div>
                <p className="text-sm text-muted-foreground">Principal</p>
                <p className="font-semibold">{formatCurrency(loanDetail.loan.principal_amount)}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Interest</p>
                <p className="font-semibold">{formatCurrency(loanDetail.loan.total_interest || 0)}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Processing Fee</p>
                <p className="font-semibold">{formatCurrency(loanDetail.loan.processing_fee || 0)}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Insurance</p>
                <p className="font-semibold">{formatCurrency(loanDetail.loan.insurance_fee || 0)}</p>
              </div>
            </div>

            {/* Payment Summary */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-4 border rounded-lg">
              <div>
                <p className="text-sm text-muted-foreground">Total Payable</p>
                <p className="font-bold text-lg">
                  {formatCurrency(loanDetail.loan.total_payable_amount)}
                </p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Total Paid</p>
                <p className="font-bold text-lg text-green-600">
                  {formatCurrency(loanDetail.summary.totalPaid)}
                </p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Outstanding</p>
                <p className="font-bold text-lg text-orange-600">
                  {formatCurrency(loanDetail.summary.totalOutstanding)}
                </p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">EMI Amount</p>
                <p className="font-bold text-lg">
                  {formatCurrency(loanDetail.loan.installment_amount)}
                </p>
              </div>
            </div>

            {/* Payment History */}
            {loanDetail.payments.length > 0 && (
              <div>
                <h4 className="font-semibold mb-3">Payment History</h4>
                <div className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Date</TableHead>
                        <TableHead>Amount</TableHead>
                        <TableHead>Mode</TableHead>
                        <TableHead>Reference</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {loanDetail.payments.map((payment: any) => (
                        <TableRow key={payment.id}>
                          <TableCell>
                            {new Date(payment.payment_date).toLocaleDateString()}
                          </TableCell>
                          <TableCell className="font-medium">
                            {formatCurrency(payment.amount_paid)}
                          </TableCell>
                          <TableCell>
                            <Badge variant="outline">{payment.payment_mode}</Badge>
                          </TableCell>
                          <TableCell className="text-muted-foreground">
                            {payment.transaction_reference || '-'}
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </div>
            )}

            {/* Penalties */}
            {loanDetail.penalties.length > 0 && (
              <div>
                <h4 className="font-semibold mb-3">Penalties Applied</h4>
                <div className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Date</TableHead>
                        <TableHead>Type</TableHead>
                        <TableHead>Amount</TableHead>
                        <TableHead>Reason</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {loanDetail.penalties.map((penalty: any) => (
                        <TableRow key={penalty.id}>
                          <TableCell>
                            {(() => {
                              if (!penalty.penalty_date) return "-";
                              const d = new Date(penalty.penalty_date);
                              return isNaN(d.getTime()) ? "-" : d.toLocaleDateString();
                            })()}
                          </TableCell>
                          <TableCell>
                            <Badge variant="destructive">{penalty.penalty_type}</Badge>
                          </TableCell>
                          <TableCell className="font-medium">
                            {formatCurrency(penalty.amount)}
                          </TableCell>
                          <TableCell className="text-muted-foreground">
                            {penalty.reason || '-'}
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      ))}

      {loans.length === 0 && (
        <Card>
          <CardContent className="py-12 text-center">
            <p className="text-muted-foreground">No loans found for this customer</p>
          </CardContent>
        </Card>
      )}

      {/* Footer - Show only on print */}
      <div className="hidden print:block text-center text-sm text-muted-foreground mt-8 pt-4 border-t">
        <p>This is a computer-generated document. No signature required.</p>
        <p className="mt-1">{settings?.company_name || 'Mit Electro World'} - {settings?.tagline || 'Loan Management System'}</p>
        <p className="mt-1">Designed & Developed by {settings?.company_name || 'Vais Engineering Pvt Ltd'}</p>
      </div>
    </div>
  );
}

